### ISSUE TITLE
Issue 2 - GIT-63

### ISSUE THREAD

**Issue by SapneshNaik** [SapneshNaik/GIT-63#3]
this is a test

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**This issue now has a bounty of $55.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://sandbox.app.gitcommits.com/issue/issue-2-git-63).
- Questions? Checkout [GitCommits Help](https://sandbox.gitcommits.com/faq)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://sandbox.app.gitcommits.com/explorer)

**Comment by angelleye-gitcommits** [comment]
### Additional Funds added to the bounty:
Additional fund of 60.00 has been added by $<a href="https://sandbox.app.gitcommits.com/profile/buyer-aaa">buyer-aaa</a>

**Comment by angelleye-gitcommits** [comment]
### Additional Funds added to the bounty:
Additional fund of 100.00 has been added by $<a href="https://sandbox.app.gitcommits.com/profile/funder2">funder2</a>

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. Open 2. **Started**  3. Submitted 4. Done

<hr>

**Work has been started.**

**<a href='https://sandbox.app.gitcommits.com/profile/cont1'>cont1</a> has been approved to start work.**

<hr />

**Message:** I approve this worker


<a href='https://sandbox.app.gitcommits.com/issue/issue-2-git-63'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/cont1'>cont1</a>, Your submission has been rejected by <a href='https://sandbox.app.gitcommits.com/profile/funder1'>funder1</a>.**
<hr />

**Message:** Pull Request has been rejected.


<a href='https://sandbox.app.gitcommits.com/issue/issue-2-git-63'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
### Additional Funds added to the bounty:
Additional fund of 60.00 has been added by $<a href="https://sandbox.app.gitcommits.com/profile/jigahoc201">jigahoc201</a>

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/cont1'>cont1</a> Work has been approved by <a href='https://sandbox.app.gitcommits.com/profile/funder1'>funder1</a>.**
<hr />

**Message:** Pull request has been approved, you will receive the payment shortly.


<a href='https://sandbox.app.gitcommits.com/issue/issue-2-git-63'>Click Here to view more</a> on GitCommits Bounty detail page.
